### PR TITLE
Landingpage/basic routes

### PR DESCRIPTION
**Pull request by Balakumar3018**
Completed landing page and basic routing.
Ignore responsiveness- 

Site preview - https://orangestore-ecommerce.netlify.app/

### CODE REVIEW

**Comment by Pratham82** [comment]
1. Routing working fine and 
2. Some UI suggestions
    - decrease the size of the brand logo, so that the navbar will be of normal size
    - If possible you can add the background tint on the main image, and make the button stand out a bit.
    
image

 Apart form this mentioned functionality is working Good to merge

**Review by Pratham82 — APPROVED** [review]

**Comment by Balakumar3018** [comment]
> 1. Routing working fine and
> 2. Some UI suggestions
>    
>    * decrease the size of the brand logo, so that the navbar will be of normal size
>    * If possible you can add the background tint on the main image, and make the button stand out a bit.
> 
> image
> 
> Apart form this mentioned functionality is working Good to merge



> ### ✅ Deploy Preview for _orangestore-ecommerce_ ready!
> Name	Link
> 🔨 Latest commit	[ae42421](https://github.com/Balakumar3018/OrangeStore/commit/ae424211fc4e2657764862231a9000eb750293ba)
> 🔍 Latest deploy log	https://app.netlify.com/sites/orangestore-ecommerce/deploys/62497fa67b71f00009648462
> 😎 Deploy Preview	https://deploy-preview-1--orangestore-ecommerce.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/orangestore-ecommerce/settings/deploys#deploy-notifications)._

k

**Comment by Balakumar3018** [comment]
Sure thanks. will add the suggestions.

**Comment by athar05** [comment]
Routing looks good. 

Few UI Sugessions: 

- The frequently purchased item section can contain a few products/categories, which upon clicking will take the user to the product page. 

- You can consider resizing the banner image, the text and the image look a little it has shrunk. 

Overall the page looks good.

**Comment by Balakumar3018** [comment]
sure will implement after product page is done.

**Pull request merged**
